package e2e;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.io.IOException;
import java.util.List;

import static org.junit.Assert.*;

/**
 * F10 — Data Management E2E Tests
 *
 * Covers: Dashboard stats, Export (4 types → CSV), Import Users/Products CSV
 * (preview + confirm/insert, invalid/empty validation), Bulk Delete, and
 * admin-only access control.
 */
public class F10_DataManagementTest extends BaseE2ETest {

    @Before
    public void setUp() {
        logout();
        loginAsStaff();
    }

    @After
    public void tearDown() {
        logout();
    }

    private void assertNoServerError() {
        String src = pageSource();
        assertFalse("Page should not 500", src.contains("HTTP ERROR 500"));
        assertFalse("Page should not 404", src.contains("HTTP ERROR 404"));
        assertFalse("Page should not show custom error page",
                src.contains("Oops! Something went wrong") ||
                src.contains("Development Error Information"));
    }

    /** Opens the data management dashboard via the page controller route. */
    private void openDashboard() {
        navigateTo("/data-management");
        // Fallback to the dashboard endpoint if the page route is unavailable
        if (pageSource().contains("HTTP ERROR 404")) {
            navigateTo("/api/dataManagement/dashboard");
        }
    }

    // ── Dashboard ─────────────────────────────────────────────────────────────

    /** TC-10-1: Data management dashboard renders without error */
    @Test
    public void testDashboardRenders() {
        openDashboard();
        assertNoServerError();
        assertTrue("Dashboard should contain management content",
                pageSource().contains("Export") || pageSource().contains("Import") ||
                pageSource().contains("Data Management"));
    }

    /** TC-10-2: Dashboard shows export + import sections */
    @Test
    public void testDashboardShowsSections() {
        openDashboard();
        assertNoServerError();
        assertTrue("Dashboard should expose an import file input",
                isElementPresent(By.name("csvFile")) && isElementPresent(By.name("entityType")));
        assertTrue("Dashboard should reference export endpoints",
                pageSource().contains("exportUsers") || pageSource().contains("Export"));
    }

    // ── Export ────────────────────────────────────────────────────────────────

    /** TC-10-3: Export users returns CSV content with the expected header */
    @Test
    public void testExportUsersReturnsCsv() {
        navigateTo("/api/dataManagement/exportUsers");
        assertNoServerError();
        String src = pageSource();
        // CSV header columns generated by CSVUtil.generateUserCSV
        assertTrue("Export users should produce CSV with Email column header",
                src.contains("Email") && src.contains("First Name") && src.contains("Last Name"));
    }

    /** TC-10-4: Export products returns CSV content */
    @Test
    public void testExportProductsReturnsCsv() {
        navigateTo("/api/dataManagement/exportProducts");
        assertNoServerError();
        assertTrue("Export products should produce CSV with Name/Category/Price headers",
                pageSource().contains("Name") && pageSource().contains("Category") &&
                pageSource().contains("Price"));
    }

    /** TC-10-5: Export orders returns CSV content */
    @Test
    public void testExportOrdersReturnsCsv() {
        navigateTo("/api/dataManagement/exportOrders");
        assertNoServerError();
        assertTrue("Export orders should produce CSV with order headers",
                pageSource().contains("Total Amount") || pageSource().contains("Order Date") ||
                pageSource().contains("Status"));
    }

    /** TC-10-6: Export access logs returns CSV content */
    @Test
    public void testExportAccessLogsReturnsCsv() {
        navigateTo("/api/dataManagement/exportAccessLogs");
        assertNoServerError();
        assertTrue("Export access logs should produce CSV with log headers",
                pageSource().contains("Action") || pageSource().contains("User ID") ||
                pageSource().contains("Timestamp"));
    }

    // ── Import ────────────────────────────────────────────────────────────────

    /** TC-10-7: Import form exists on the dashboard */
    @Test
    public void testImportFormExists() {
        openDashboard();
        assertNoServerError();
        assertTrue("Data management page should have a CSV file input",
                isElementPresent(By.name("csvFile")));
        assertTrue("Data management page should have an entityType selector",
                isElementPresent(By.name("entityType")));
    }

    /** TC-10-8: Import users with valid CSV shows preview of the uploaded row */
    @Test
    public void testImportUsersValidCSVShowsPreview() throws IOException {
        openDashboard();

        String suffix = java.util.UUID.randomUUID().toString().substring(0, 6);
        String email = "e2e-import-" + suffix + "@test.com";
        String validCsv = "Email,First Name,Last Name,Phone,Is Active\n" +
                email + ",Import,User,+61400000001,true\n";

        selectOption("entityType", "Users");
        uploadCSV("csvFile", validCsv);

        List<WebElement> submitBtns = driver.findElements(
                By.cssSelector("form[action*='import'] [type='submit'], form[action*='import'] button[type='submit']"));
        if (!submitBtns.isEmpty()) {
            submitBtns.get(0).click();
            assertNoServerError();
            String src = pageSource();
            // The preview page should render the uploaded email + a Confirm Import action
            assertTrue("Import preview should show the uploaded row and a confirm action",
                    (src.contains(email) || src.contains("Preview")) &&
                    (src.contains("Confirm Import") || src.contains("Confirm")));
        }
    }

    /** TC-10-9: Import → confirm actually inserts the user */
    @Test
    public void testImportUsersConfirmInserts() throws IOException {
        openDashboard();

        String suffix = java.util.UUID.randomUUID().toString().substring(0, 6);
        String email = "e2e-confirm-" + suffix + "@test.com";
        String validCsv = "Email,First Name,Last Name,Phone,Is Active\n" +
                email + ",Confirm,User,+61400000002,true\n";

        selectOption("entityType", "Users");
        uploadCSV("csvFile", validCsv);

        List<WebElement> submitBtns = driver.findElements(
                By.cssSelector("form[action*='/import'] [type='submit'], form[action*='/import'] button[type='submit']"));
        if (!submitBtns.isEmpty()) {
            submitBtns.get(0).click();
            assertNoServerError();

            // Confirm the import
            List<WebElement> confirmBtns = driver.findElements(
                    By.cssSelector("form[action*='confirmImport'] [type='submit'], form[action*='confirmImport'] button[type='submit']"));
            if (!confirmBtns.isEmpty()) {
                confirmBtns.get(0).click();
                assertNoServerError();
                assertTrue("Confirm import should report records imported",
                        pageSource().contains("imported") || pageSource().contains("record") ||
                        pageSource().contains("Import complete"));
            }
        }
    }

    /** TC-10-10: Import with invalid CSV headers shows an error (no 500) */
    @Test
    public void testImportInvalidCSVHeadersShowsError() throws IOException {
        openDashboard();

        String invalidCsv = "WrongCol1,WrongCol2,WrongCol3\nval1,val2,val3\n";

        selectOption("entityType", "Users");
        uploadCSV("csvFile", invalidCsv);

        List<WebElement> submitBtns = driver.findElements(
                By.cssSelector("form[action*='/import'] [type='submit'], form[action*='/import'] button[type='submit']"));
        if (!submitBtns.isEmpty()) {
            submitBtns.get(0).click();
            assertNoServerError();
            String src = pageSource();
            assertTrue("Invalid CSV headers should produce an error message",
                    src.contains("Invalid") || src.contains("Expected") ||
                    src.contains("error") || src.contains("Error"));
        }
    }

    /** TC-10-11: Import products with valid CSV shows preview */
    @Test
    public void testImportProductsValidCSV() throws IOException {
        openDashboard();

        String validCsv = "Name,Category,Price,Stock Quantity,Description\n" +
                "E2E Test Product,IoT,49.99,5,E2E test description\n";

        selectOption("entityType", "Products");
        uploadCSV("csvFile", validCsv);

        List<WebElement> submitBtns = driver.findElements(
                By.cssSelector("form[action*='/import'] [type='submit'], form[action*='/import'] button[type='submit']"));
        if (!submitBtns.isEmpty()) {
            submitBtns.get(0).click();
            assertNoServerError();
            assertTrue("Product import should show a preview",
                    pageSource().contains("E2E Test Product") || pageSource().contains("Preview"));
        }
    }

    // ── Bulk Delete ───────────────────────────────────────────────────────────

    /** TC-10-12: Bulk delete section exists */
    @Test
    public void testBulkDeleteSectionExists() {
        openDashboard();
        assertNoServerError();
        assertTrue("Data management page should have a bulk delete form",
                isElementPresent(By.cssSelector("form[action*='bulkDelete']")) ||
                isElementPresent(By.name("deleteType")));
    }

    // ── Access control ─────────────────────────────────────────────────────────

    /** TC-10-13: Unauthenticated access to dashboard is blocked */
    @Test
    public void testUnauthenticatedCannotAccessDashboard() {
        logout();
        navigateTo("/api/dataManagement/dashboard");
        boolean blocked = currentUrl().contains("login") ||
                pageSource().contains("login") ||
                pageSource().contains("401");
        assertTrue("Unauthenticated access to data management should be blocked", blocked);
    }

    /** TC-10-14: Customer cannot access data management */
    @Test
    public void testCustomerCannotAccessDataManagement() {
        logout();
        loginAsCustomer();
        navigateTo("/api/dataManagement/dashboard");
        boolean blocked = currentUrl().contains("login") ||
                pageSource().contains("403") ||
                pageSource().contains("Unauthorized") ||
                !currentUrl().contains("dataManagement");
        assertTrue("Customer role should NOT access data management", blocked);
    }
}
